/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import br.com.senac.biblioteca.projeto.data;

/**
 *
 * @author Aluno TDS
 */
public class JFHome extends javax.swing.JFrame {

    JFCatalog catalog;
    JFLending lending;
    private final data data = new data();
    
    /**
     * Creates new form Home
     */
    public JFHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBCatalog = new javax.swing.JButton();
        JBBorrow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JBCatalog.setText("Catalog");
        JBCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCatalogActionPerformed(evt);
            }
        });

        JBBorrow.setText("Borrow");
        JBBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBorrowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBCatalog)
                .addGap(18, 18, 18)
                .addComponent(JBBorrow)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBCatalog)
                    .addComponent(JBBorrow))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public data getData(){
        return this.data;
    }
    
    private void JBCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCatalogActionPerformed
        if(this.catalog!= null){
        this.catalog.setVisible(false);
        }        
        this.catalog = new JFCatalog(this);
        this.catalog.setVisible(true);
    }//GEN-LAST:event_JBCatalogActionPerformed

    private void JBBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBorrowActionPerformed
        if(this.lending!= null){
        this.lending.setVisible(false);
        }        
        this.lending = new JFLending(this);
        this.lending.setVisible(true);
    }//GEN-LAST:event_JBBorrowActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBBorrow;
    private javax.swing.JButton JBCatalog;
    // End of variables declaration//GEN-END:variables
}
