/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package swing;

import br.com.senac.biblioteca.projeto.data;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import model.Lending;

/**
 *
 * @author Aluno TDS
 */
public class JFLending extends  javax.swing.JFrame {

    data data;
    /**
     * Creates new form JDLending
     */
    public JFLending(JFHome parent) {
        super();
        this.data = parent.getData();
        initComponents();
        this.JTResults.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e) {
                int index = JTResults.getSelectedRow();
                if(index >= 0) {
                   Lending lending = data.getLibrary().getLendings().get(index);
                    JTFId.setText(String.valueOf(lending.getId()));
                    JTFTitle.setText(lending.getTitle());
                    JTFAuthor.setText(lending.getAuthor());
                    JTFDate.setText(lending.getDate());
                    JTFClient.setText(lending.getClient());
                    JCBCathegory.setSelectedItem(lending.getCathegory());
                    JCBReturned.setSelected(lending.isReturned());
                }
            }
        });
    }
    
    public void clear() {
        this.JTFTitle.setText("");
        this.JTFAuthor.setText("");
        this.JTFId.setText("");
        this.JCBCathegory.setSelectedItem("Infantil");
        JCBReturned.setSelected(false);
        this.JTFDate.setText("");
        JTFClient.setText("");
        this.JTResults.setModel(initTable());
        //this.jTableCatalogo.clearSelection();
    }
    
    public JTLendings initTable (){
        return new JTLendings(this.data.getLibrary().getLendings());
    }
    
    public Lending createLending (){      
        Lending output = new Lending(this.JTFTitle.getText(), this.JTFAuthor.getText(),
        this.JCBCathegory.getSelectedItem().toString(), this.JTFDate.getText(), this.JTFClient.getText());
        output.setReturned(this.JCBReturned.isSelected());
        if(!this.JTFId.getText().isEmpty())
            output.setId(Integer.parseInt(this.JTFId.getText()));

        return output;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTResults = new javax.swing.JTable();
        JLTitle = new javax.swing.JLabel();
        JLAuthor = new javax.swing.JLabel();
        JLDate = new javax.swing.JLabel();
        JCBCathegory = new javax.swing.JComboBox<>();
        JLId = new javax.swing.JLabel();
        JTFTitle = new javax.swing.JTextField();
        JTFAuthor = new javax.swing.JTextField();
        JTFDate = new javax.swing.JTextField();
        JTFId = new javax.swing.JTextField();
        JBSave = new javax.swing.JButton();
        JBDelete = new javax.swing.JButton();
        JBSearch = new javax.swing.JButton();
        JLDate1 = new javax.swing.JLabel();
        JLClient = new javax.swing.JLabel();
        JTFClient = new javax.swing.JTextField();
        JCBReturned = new javax.swing.JCheckBox();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JTResults.setModel(initTable());
        jScrollPane1.setViewportView(JTResults);

        JLTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLTitle.setText("Title");

        JLAuthor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLAuthor.setText("Author");

        JLDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLDate.setText("Cathegory");

        JCBCathegory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infantil", "Religião", "Fantasia", "Ficção", "Auto-ajuda", "Informática" }));

        JLId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLId.setText("ID");

        JTFAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFAuthorActionPerformed(evt);
            }
        });

        JTFDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFDateActionPerformed(evt);
            }
        });

        JTFId.setEditable(false);

        JBSave.setText("Save");
        JBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSaveActionPerformed(evt);
            }
        });

        JBDelete.setText("Delete");
        JBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBDeleteActionPerformed(evt);
            }
        });

        JBSearch.setText("Search");
        JBSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSearchActionPerformed(evt);
            }
        });

        JLDate1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLDate1.setText("Date");

        JLClient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLClient.setText("Client");

        JTFClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFClientActionPerformed(evt);
            }
        });

        JCBReturned.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JCBReturned.setText("Returned");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JLTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFTitle))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JLAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFAuthor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLId, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFId, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JLDate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCBCathegory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JCBReturned)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBSave)
                        .addGap(18, 18, 18)
                        .addComponent(JBDelete)
                        .addGap(18, 18, 18)
                        .addComponent(JBSearch))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLClient, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFClient))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFDate)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLClient, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBCathegory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBSave)
                    .addComponent(JBDelete)
                    .addComponent(JBSearch)
                    .addComponent(JCBReturned))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSaveActionPerformed
        this.data.getLibrary().editLending(createLending());
        clear();
    }//GEN-LAST:event_JBSaveActionPerformed

    private void JTFAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFAuthorActionPerformed

    private void JTFDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFDateActionPerformed

    private void JBSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSearchActionPerformed
        JDSearch dialog = new JDSearch(this);
        dialog.setVisible(true);     
    }//GEN-LAST:event_JBSearchActionPerformed

    private void JTFClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFClientActionPerformed

    private void JBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDeleteActionPerformed
        if(this.JTFId.getText().isEmpty())
            return;
        this.data.getLibrary().removeLending(createLending());
        clear();
    }//GEN-LAST:event_JBDeleteActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBDelete;
    private javax.swing.JButton JBSave;
    private javax.swing.JButton JBSearch;
    protected javax.swing.JComboBox<String> JCBCathegory;
    private javax.swing.JCheckBox JCBReturned;
    private javax.swing.JLabel JLAuthor;
    private javax.swing.JLabel JLClient;
    private javax.swing.JLabel JLDate;
    private javax.swing.JLabel JLDate1;
    private javax.swing.JLabel JLId;
    private javax.swing.JLabel JLTitle;
    protected javax.swing.JTextField JTFAuthor;
    private javax.swing.JTextField JTFClient;
    private javax.swing.JTextField JTFDate;
    private javax.swing.JTextField JTFId;
    protected javax.swing.JTextField JTFTitle;
    private javax.swing.JTable JTResults;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
